NeRF review
creatis-myriad/creatis-myriad.github.io pull request #105
Opened 2023-02-01 17:53 UTC by maylis-j

Biblio review de jeudi 02/02

2023-02-02 09:43 UTC, PierreRouge requested changes
I made some comments, but I'm not familiar with this topic, so maybe you will find them irrelevant. But I do think it would be nice to add more context.

2023-02-02 09:43 UTC, PierreRouge commented on collections/_posts/2023-01-31-NeRF.md
> +# Highlights
Maybe it would be nice to add some context because I think that most of the participants will not be familiar with this topic =)

2023-02-02 09:43 UTC, PierreRouge commented on collections/_posts/2023-01-31-NeRF.md
> +
I suggest making this part clearer by separating training and inference phase.

2023-02-02 09:43 UTC, PierreRouge commented on collections/_posts/2023-01-31-NeRF.md
> +Each scene is represented by an 8 fully-connected layers MLP network $$ F_\Theta : (\boldsymbol{x},\boldsymbol{d}) \rightarrow (RGB,\sigma)$$ with $$x$$ being the postion, $$d$$ the direction and $$\
I would suggest rephrasing this part like this:
```suggestion
One MLP network with 8 fully-connected layers is learned for each scene. This MLP learn to map a position $$x$$ and a direction $$d$$ to a density $$\sigma$$ and color values $$RGB$$ :
$$ F_\Theta : (\boldsymbol{x},\boldsymbol{d}) \rightarrow (RGB,\sigma)$$
```

2023-02-02 09:43 UTC, PierreRouge commented on collections/_posts/2023-01-31-NeRF.md
> +Note that the density does not appear in this loss, it is used to compte de RGB colors.
Maybe a little mistake here
```suggestion
Note that the density does not appear in this loss, it is used to compute the RGB colors.
```

2023-02-09 12:14 UTC, nathanpainchaud approved these changes

2023-02-09 12:53 UTC, PierreRouge approved these changes

2023-02-09 14:04 UTC, merged