SAM aka Segment Anything Model
creatis-myriad/creatis-myriad.github.io pull request #127
Opened 2023-04-11 15:04 UTC by JulietteMoreau

Review for the 13th april on SAM, the new META model released last Thursday.

2023-04-11 16:28 UTC, nathanpainchaud commented
@JulietteMoreau Great choice of paper to review! I heard about this paper earlier today and I was going to check it out on my own, but now I'll just wait for your review :wink:

2023-04-12 13:37 UTC, Volkaa requested changes
Very nice review, a very interesting recent article. Let's hope we won't be au chomage by the end of the PhD.

2023-04-12 13:37 UTC, Volkaa commented on collections/_posts/2023-04-11-SAM.md
> +It still has some limitations, there are some errors missing small structures or creating small disconnected components, and does not produce boundaries as crisply as more computationally intensive m
```suggestion
It still has some limitations, there are some errors missing small structures or creating small disconnected components and does not produce boundaries as crisply as more computationally intensive methods. Given the fact that it is a very generic segmentation model whose goal is to perform with zero transfer learning, it is expected that all dedicated interactive segmentation methods outperform SAM. Another limitation is the computational time: it is said to be real-time but it is not really the case when using a heavy image encoder. Finally even if SAM performs many tasks, it is not easy to design simple prompts that implement semantic and panoptic segmentation.
```

2023-04-13 08:46 UTC, Volkaa approved these changes

2023-04-13 08:46 UTC, merged

2023-04-13 12:14 UTC, nathanpainchaud reviewed
A reminder of some typos/confusing phrasing pointed out during the presentation.

2023-04-13 12:14 UTC, nathanpainchaud commented on collections/_posts/2023-04-11-SAM.md
> +Models are almost always dedicated to a particular task, but here the foundation model trained on a very large dataset is then adapted to many tasks. However, generally foundation models are auto-sup
wherease -> whereas
+
To clear the confusion with MAE being supervised or not as pointed out by Gaspard, I would suggest to rephrase things in the folloing way:
_it is initialised with a MAE trained using supervised labels._