Transformer Interpretability Beyond Attention Visualization
creatis-myriad/creatis-myriad.github.io pull request #129
Opened 2023-04-25 09:24 UTC by nathanpainchaud

2023-04-26 08:22 UTC, HangJung97 requested changes
Great review! Just a few typos.

2023-04-26 09:18 UTC, nathanpainchaud commented on collections/_posts/2023-04-24-TransformerInterpretability.md
> +by the mean value) and an NLP task (extraction of rationales supporting the binary sentiment classification on the Movie
That was voluntary, and I would not consider this a typo :wink: Normally you use _an_ when the next word starts with a vowel sound (in this case _N_ is pronounced _[en]_) even if the letter itself is a consonant.

Here is a [post on the subject](https://www.scribbr.com/commonly-confused-words/a-vs-an/#:~:text=Revised%20on%20March%2011%2C%202023,%2C%E2%80%9D%20%E2%80%9Ci%E2%80%9D).) with the closest example I could find to the current case.

2023-04-26 09:22 UTC, HangJung97 commented on collections/_posts/2023-04-24-TransformerInterpretability.md
> +by the mean value) and an NLP task (extraction of rationales supporting the binary sentiment classification on the Movie
Thanks for pointing this out. Didn't know this applies to acronym as well.

2023-04-26 09:26 UTC, nathanpainchaud commented on collections/_posts/2023-04-24-TransformerInterpretability.md
> +encoding of the class for which of the class w.r.t. which the relevance should be computed.
That depends what you mean by _target_. It's not target in the sense of the groundtruth class for the current input, but rather in the sense of the target class for which you want to measure the network's attention.

But other than that small clarification, your interpretation is spot on! I also noticed that the end of the sentence is all mangled up (a mash up of different ways I tried to formulate this), so it was not easy decipher. I've rephrased things to be clearer :wink:

2023-04-26 09:30 UTC, HangJung97 commented on collections/_posts/2023-04-24-TransformerInterpretability.md
> +encoding of the class for which of the class w.r.t. which the relevance should be computed.
For _target_, I mean the class you want to measure the attention. The rephrased sentence looks good and clear to me.

2023-04-26 09:30 UTC, HangJung97 approved these changes

2023-04-27 06:08 UTC, OlivierBernard approved these changes
Excellent review ! I found one typo, but on a figure ;)))

2023-04-27 06:09 UTC, merged