First version of the paper for tomorrow's bibliography club
creatis-myriad/creatis-myriad.github.io pull request #143
Opened 2023-07-05 13:26 UTC by maylis-j

Don't hesitate to note whenever something is unclear :)

2023-07-05 15:10 UTC, juliapg commented on collections/_posts/2023-06-30-Shape_Aware_organ_segmentation.md
> +* Compared to using only the segmentation map, the results have less false positives, and reduce the Hausorff Distance (HD)
Hausdorff

2023-07-06 08:02 UTC, Morgane-des-Ligneris commented on collections/_posts/2023-06-30-Shape_Aware_organ_segmentation.md
> +**Note**: the authors also tried with two output branches but had better results with only one output
```suggestion
> **Note**: the authors also tried with two output branches but had better results with only one output
```

2023-07-06 08:04 UTC, Morgane-des-Ligneris commented on collections/_posts/2023-06-30-Shape_Aware_organ_segmentation.md
> +**Note**: Average Symmetric Surface Distance (ASD or ASSD) is the average distance between boundary points from the predicted mask and from the ground truth mask.
```suggestion
> **Note**: Average Symmetric Surface Distance (ASD or ASSD) is the average distance between boundary points from the predicted mask and from the ground truth mask.
```

2023-07-06 08:05 UTC, Morgane-des-Ligneris requested changes
very clear :) !

2023-07-06 10:39 UTC, Morgane-des-Ligneris approved these changes

2023-07-06 10:44 UTC, merged