Multimodal autoencoder
creatis-myriad/creatis-myriad.github.io pull request #145
Opened 2023-07-19 13:51 UTC by OlivierBernard

2023-07-20 11:24 UTC, nathanpainchaud requested changes
Great post as always! Just a few typos and phrasing to fix.

2023-07-20 11:24 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
> +- $$p_I \in \mathbb{R}^{D}$$ used for the aggregation of visual information
Missing word:
```suggestion
- $$p_I \in \mathbb{R}^{D}$$ is used for the aggregation of visual information
```

2023-07-20 11:24 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
> +- Each input text is tokenize to subword tokens $${w_1,\cdots;w_M}$$ by WordPiece, where tokens $$w_m \in \mathbb{R}^{V}$$ are represented in one-hot form and $$V$$ is the vocabulary size
Conjugation:
```suggestion
- Each input text is tokenized to subword tokens $${w_1,\cdots;w_M}$$ by WordPiece, where tokens $$w_m \in \mathbb{R}^{V}$$ are represented in one-hot form and $$V$$ is the vocabulary size
```

2023-07-20 11:24 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
> +- Images and texts are abstracted at different levels, with pixels having a lower semantic level than token of texts.
Phrasing:
```suggestion
- Images and texts are abstracted at different levels, with pixels having a lower semantic level than text tokens.
```

2023-07-20 11:24 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
> +* Pre-training in a self-supervised way using maskink strategy appears to be relevant
Typo:
```suggestion
* Pre-training in a self-supervised way using a masking strategy appears to be relevant
```

2023-07-20 11:24 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
> +* Exploiting embedings at different levels of abstraction for images and text would seem to be a good approach
Typo:
```suggestion
* Exploiting embeddings at different levels of abstraction for images and text would seem to be a good approach
```

2023-07-20 11:26 UTC, nathanpainchaud requested changes
I missed this typo when simply reading the post.

2023-07-20 11:26 UTC, nathanpainchaud commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
There's a typo in the name of the fle as well :sweat_smile: _Mutlimodal_ -> _Multimodal_

2023-07-27 12:45 UTC, OlivierBernard commented on collections/_posts/2023-07-17-Mutlimodal-AutoEncoder.md
I change the filename, thanks !

2023-07-28 12:03 UTC, nathanpainchaud approved these changes

2023-07-28 12:04 UTC, merged