Latent diffusion models
creatis-myriad/creatis-myriad.github.io pull request #157
Opened 2024-01-09 23:50 UTC by olivier-bernard-creatis

2024-01-10 19:35 UTC, Celia-Gjt commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +author: "Celia Goujeat, Olivier Bernard"
tu as fais ce post seul  finalement :)

2024-01-10 19:35 UTC, Celia-Gjt commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +* Diffusion models (DMs) are applied in the latent space of powerfull pretrained autoencoders
typo : powerfull -> powerful

2024-01-10 19:35 UTC, Celia-Gjt commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +* use of images of landscapes paired with semantic maps
use ->Use pour la cohérence avec la suite

2024-01-10 20:10 UTC, olivier-bernard-creatis commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +author: "Celia Goujeat, Olivier Bernard"
Oui, j'avais initialiement prévu de le faire avec toi, mais vu que personne ne s'est proposé pour faire un post cette semaine, je me suis motivé pour l'avancé et le terminé rapidement ;)

2024-01-11 13:00 UTC, nathanpainchaud requested changes
Just a few quick typos/phrasing comments. Otherwise everything's looking good :)

2024-01-15 09:14 UTC, olivier-bernard-creatis commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +* two different kinds of regularizations are tested to avoid high-variance latent spaces: *KL-reg* which imposes a slight KL-penality towards a standard normal on the learned latent, and *VQ-reg* whi
done

2024-01-15 09:15 UTC, olivier-bernard-creatis commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +## Model artchitecture
done

2024-01-15 09:15 UTC, olivier-bernard-creatis commented on collections/_posts/2023-12-19-latent-diffusion-models.md
> +* FID: Fréchet Inception Distance: captures the similarity of generated images to real ones better than the more conventional Inception Score
done

2024-01-15 12:47 UTC, nathanpainchaud approved these changes

2024-01-15 12:48 UTC, merged