post bss-vae
creatis-myriad/creatis-myriad.github.io pull request #166
Opened 2024-03-11 10:04 UTC by juliapg

2024-03-11 15:48 UTC, RomainDeleat-besson requested changes
Very good and comprehensible post !
Minor adjustments to do.

2024-03-11 15:48 UTC, RomainDeleat-besson commented on collections/_posts/2024-02-27-BSS-with-VAE.md
> +$$p(z) = \prod_{k=1}^K p(z_k) = \prod_{k=1}^K N(z_k | 0, I).$$
I will put this section in the encoder or loss function section

2024-03-14 12:00 UTC, ThierryJudge approved these changes

2024-03-14 12:02 UTC, RomainDeleat-besson approved these changes

2024-03-14 12:03 UTC, merged