Post: Diffusion autoencoder
creatis-myriad/creatis-myriad.github.io pull request #185
Opened 2024-10-08 13:13 UTC by RomainDeleat-besson

My post on **Diffusion Autoencoders: Toward a Meaningful and Decodable Representation**.

Thanks in advance for your time and help to make this post incredible !

2024-10-09 16:21 UTC, Celia-Gjt requested changes
Super review, hâte d'écouter ta présentation demain :)

2024-10-09 16:21 UTC, Celia-Gjt commented on collections/_posts/2024-10-07-Diffusion_Autoencoders.md
> +
Avoir écrit le forward process du DDPM et du DDIM de la sorte sous deux formes différentes donne l'impression qu'il s'agit de deux formules différentes. Hors, sauf erreur de ma part le forward process est exactement le même pour les deux, seul le reverse process change (on peut donc, sans ré-entraîner le modèle, faire du DDPM ou du DDIM).

2024-10-09 16:21 UTC, Celia-Gjt commented on collections/_posts/2024-10-07-Diffusion_Autoencoders.md
> +> Note that the stochastic encoder is not used during training and is used to compute $$ x_T $$ for tasks that require exact reconstruction or inversion, such as real-image manipulation.
Je n'ai pas vraiment compris comment le decodeur "stochastic" pouvait ne pas être utilisé pendant l'entraînement concrètement, mais on pourra peut être en rediscuter demain.

2024-10-09 16:21 UTC, Celia-Gjt commented on collections/_posts/2024-10-07-Diffusion_Autoencoders.md
> +## high-level semantics and low-level stochastic variations
```suggestion
## High-level semantics and low-level stochastic variations
```

2024-10-10 07:13 UTC, RomainDeleat-besson commented on collections/_posts/2024-10-07-Diffusion_Autoencoders.md
> +
Exact, le forward process est le même.
En l'occurence, même si l'écriture est (un peu) différente, c'est bien la même chose.
J'ai repris les notations des 2 articles (celle des DDIM et celle de ma review).
Mais je peux comprendre que ca induit en erreur.

Je vais rajouter une info pour clarifier le tout !

2024-10-10 07:14 UTC, RomainDeleat-besson commented on collections/_posts/2024-10-07-Diffusion_Autoencoders.md
> +> Note that the stochastic encoder is not used during training and is used to compute $$ x_T $$ for tasks that require exact reconstruction or inversion, such as real-image manipulation.
Alors ici c'est l'encodeur stochastic.
Et je suis pas sûr d'avoir bien compris cette partie aussi, donc oui le but c'est un peu d'en discuter pendant la review.

2024-10-10 09:41 UTC, Celia-Gjt approved these changes

2024-10-10 09:43 UTC, RomainDeleat-besson commented
Merci pour la review !

2024-10-10 09:43 UTC, merged