Combat harmonization
creatis-myriad/creatis-myriad.github.io pull request #192
Opened 2024-11-26 15:37 UTC by baptisp

Merge request pour la review de jeudi 28/11/2024 sur la méthode d'harmonisation ComBat.

Le papier original est assez long, il y a beaucoup d'expériences et de résultats pour montrer que ComBat est plutôt fiable par rapport à l'état de l'art. Peut-être que tout n'est pas nécessaire.

Tout critique ou suggestion d'amélioration est la bienvenue pour ce premier post du doctorant !

2024-11-26 17:20 UTC, bayaca requested changes
very in-depth an thorough review, well done !

for the oral presentation, maybe focus on the intuition behind the technical details, as you did in the discussion section, and invite the listeners to refer to the post for further details

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +For voxel $\nu=1,2,...,p$, let $y_{ij\nu}$ represent the diffusion metric measure (FA for e.g.) at voxel $\nu$ for the scan $j$ at site $i$. ComBat posits the fllowing location and scale (L/S) adjust
```suggestion
For voxel $\nu=1,2,...,p$, let $y_{ij\nu}$ represent the diffusion metric measure (FA for e.g.) at voxel $\nu$ for the scan $j$ at site $i$. ComBat posits the following location and scale (L/S) adjustement model:
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +<!-- Show how the compute the estimates with the bayesian framework -->
```suggestion
<!-- Show how to compute the estimates with the bayesian framework -->
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +2) For each site, they define the site-specific signal silver-standard to be the k=5000 voxels with the highest t-sttistics in magnitude.
```suggestion
2) For each site, they define the site-specific signal silver-standard to be the k=5000 voxels with the highest t-statistics in magnitude.
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +Figure 4a shows a t-statistic at each voxel to measure the association of the DTI scalar values with site. A voxel is significant is the p-value calculated from the two-sample t-test is less than 0.0
```suggestion
Figure 4a shows a t-statistic at each voxel to measure the association of the DTI scalar values with site. A voxel is significant if the p-value calculated from the two-sample t-test is less than 0.05, after correcting for multiple comparisons using Bonferroni correction. They authors don't explain how they realize the correction in practice. For more details about how they perform a two-sample t-statistics with DTI data, see Figure A.3.
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +To evaluate the robustness of the different harmonization methods in the presences of statistical  confounding between imaging site and age (that is when age is unbalanced with respect to site), the
```suggestion
To evaluate the robustness of the different harmonization methods in the presences of statistical confounding between imaging site and age (that is when age is unbalanced with respect to site), the authors selected different subsets of the data to create confounding scenarios.
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +Results for raw data are consitent: positive (resp. negative) confoundind shifts the effect size positively (resp negatively).
```suggestion
Results for raw data are consitent: positive (resp. negative) confounding shifts the effect size positively (resp negatively).
```

2024-11-26 17:20 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +* The authors shows that combining the two studies without proper harmonization led to a decrease in power od detecting voxels associated with age.
```suggestion
* The authors show that combining the two studies without proper harmonization led to a decrease in power of detecting voxels associated with age.
```

2024-11-26 17:25 UTC, bayaca commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +* ComBat performs the best at removing site effects in FA and MD.
same comment for the other metrics

2024-11-27 08:11 UTC, MathildeDupouy approved these changes
Thanks for this really extensive review !

on my opinion, the points to outline for the oral presentations will be the technique in itself and also the different ways of evaluating an harmonization methods. I think you can even add an highlight like "An extensive evaluation and comparison of several methods is carefully conducted" because I feel like this is a strength of the paper, isn't it ?

I hope my reviews will be helpful and I am looking forward for your explanations on Thursday !

2024-11-27 08:11 UTC, MathildeDupouy commented on collections/_posts/2024-11-28-ComBat-Harmonization.md
> +* The authors shows that combining the two studies without proper harmonization led to a decrease in power od detecting voxels associated with age.
power **of** detecting

2024-11-28 07:51 UTC, bayaca approved these changes
👍

2024-11-28 11:42 UTC, merged