recommand sourcing bashrc in contributor's guide
creatis-myriad/creatis-myriad.github.io pull request #28
Opened 2022-06-09 16:20 UTC by emmanuelrouxfr

2022-06-09 16:35 UTC, nathanpainchaud requested changes
Thanks for the suggestion! Just two simple recommendations to avoid any possible confusion on the purpose of each command.

2022-06-09 16:35 UTC, nathanpainchaud commented on how-to-contribute.md
> +# source your bashrc to make it visible to your system now
```suggestion
# source your bashrc to make it visible to your current shell
```

2022-06-10 07:23 UTC, emmanuelrouxfr commented on how-to-contribute.md
> +# Add rbenv to your bashrc (and source it) to make it visible to your system each time you restart your machine (and now)
All good, it's clearer !

2022-06-10 07:30 UTC, nathanpainchaud approved these changes
All good now! Thanks for the quick turn-around!

2022-06-10 07:30 UTC, merged