C2FTrans: Coarse-to-Fine Transformers for Medical Image Segmentation
creatis-myriad/creatis-myriad.github.io pull request #51
Opened 2022-07-14 11:28 UTC by HangJung97

2022-07-19 21:12 UTC, nathanpainchaud requested changes
Good review. Just a few quick corrections and a slight clarification in one part of the text, and it'll be good to go :slightly_smiling_face:

2022-07-19 21:12 UTC, nathanpainchaud commented on collections/_posts/2022-07-07-C2FTrans-Segmentation.md
> +Three functionalities of $$ F_{CGT} $$:
From the text before: 

> To obtain the final CGT output, $$ F_{CGT} $$

I understand that F_CGT is the output. But in that case, I'm not sure I get what _functionalities_ an output can have? As in, what _functionalities_ can data have? Would it be more appropriate to talk about what transformations produced the output or downstream tasks? So could you please elaborate on this to make things clearer?

2022-07-19 21:12 UTC, nathanpainchaud commented on collections/_posts/2022-07-07-C2FTrans-Segmentation.md
> +For each transformer head, the self-attention, $$ F_{sa,k} $$ is computed. Then, the outputs of all head are concatenated to form $$ F_{sa} $$. Just like the CGT, the final BLT output, $$ F_{BLT} $$
Typo
```suggestion
For each transformer head, the self-attention, $$ F_{sa,k} $$ is computed. Then, the outputs of all the heads are concatenated to form $$ F_{sa} $$. Just like the CGT, the final BLT output, $$ F_{BLT} $$ will be used to generate the low-res probability map for loss computation and upsampled to produce the full scale probability map.
```

2022-07-19 21:12 UTC, nathanpainchaud commented on collections/_posts/2022-07-07-C2FTrans-Segmentation.md
> +The introduction of C2F transformer in medical image segmentation is interesting, especially the Cross-scale Global Transformer. However, the paper is not well written as some important details are m
Typo + missing words
```suggestion
The introduction of C2F transformer in medical image segmentation is interesting, especially the Cross-scale Global Transformer. However, the paper is not well written as some important details are missing, e.g. the generation and combination of $$ Q $$, $$ K $$, and $$ V $$ of different dimension in the CGT. Moreover, there are some contradictions between some of the steps described in their paper and their GitHub code. 
```

2022-07-19 21:12 UTC, nathanpainchaud commented on collections/_posts/2022-07-07-C2FTrans-Segmentation.md
> +
Unnecessary blank lines at the end of the file.

2022-07-20 06:55 UTC, HangJung97 commented
Thanks, Nathan. All the suggested changes have been applied! 😀

2022-07-20 07:42 UTC, nathanpainchaud approved these changes
Thansk for the quick turnaround :)

2022-07-20 07:43 UTC, merged