Tuto vae
creatis-myriad/creatis-myriad.github.io pull request #62
Opened 2022-09-15 11:59 UTC by OlivierBernard

Let's start the show ;)

2022-09-16 08:50 UTC, jodoin requested changes

2022-09-16 08:50 UTC, jodoin commented on collections/_tutorials/2022-09-12-tutorial-vae.md
> +2. We use a new (simpler) distribution $$q(z)$$ to estimate $$p(z/x)$$
aussi, personnellement, j'écrirais ici q(z/x) et non q(z).

2022-09-16 08:50 UTC, jodoin commented on collections/_tutorials/2022-09-12-tutorial-vae.md
> +KL divergence allows to measure a distance between two distributions with the following properties:
positive 

because Hpq>Hp

2022-09-16 17:03 UTC, OlivierBernard reviewed
All the comments have been taking into account

2022-09-16 17:05 UTC, OlivierBernard commented
@Nathan: I am not still 100% happy with my post, I will integrate others concepts to strengthen it ! Let's wait for my next commit before doing your review

2022-09-20 12:37 UTC, jodoin approved these changes

2022-09-22 07:48 UTC, merged

2022-09-22 12:01 UTC, nathanpainchaud reviewed
Great tutorial! Just a few small comments related to typos/formatting ;)

Also, I haven't looked through all the figures you've produced for the tutorial, but some (e.g. _decoder_illustration_ and _decoder_illustration_2_ ) are not used in the tutorial anymore. Maybe they were in previous WIP versions? So I would suggest you delete the unused figures to avoid taking up unnecessary space on the repo.